name: workflow dast
on: push
jobs:
  DAST:
    runs-on: ubuntu-22.04
    steps:
      - name: PULL TO CONTAINER
        uses: actions/checkout@v4  
      - name: scan-push
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --log-level=5 --branch=master   --results=verified,unknown